/* This file is generated by tools/textbook-pack/build-maynard-direct-refs.ts. Do not edit by hand. */

import type { GrammarItem } from './curriculumService'

export type MaynardDirectRef = NonNullable<GrammarItem['maynardRef']> & {
  sourceKind: 'direct'
  confidence: 'direct' | 'keyword'
  sourceId: string
  pageStart?: number
  pageEnd?: number
  aliases: string[]
}

const MAYNARD_DIRECT_REFS: MaynardDirectRef[] = [
  {
    "topicId": "verb_grammar/being_です_だ_ある_いる",
    "title": "Being: です, だ, ある, いる",
    "excerpt": "Being:です,だ,ある,いる We already looked at です and f, but we haven't really looked at how they fit together with other existential verbs, and how each differs from the other.",
    "examples": [
      {
        "japanese": "bases areなら,なり，なる,なれ andなれ.",
        "english": "While typically used in combination with the verb particle lC, it can"
      },
      {
        "japanese": "力になります。",
        "english": "\"(This) will become (our) strength\"."
      },
      {
        "japanese": "力となります。",
        "english": "\"(This) will be (our) strength\"."
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 92,
    "pageEnd": 93,
    "aliases": [
      "Being: です, だ, ある, いる",
      "です",
      "だ",
      "ある",
      "いる",
      "がある",
      "がいる",
      "じゃない",
      "じゃありません",
      "ではない"
    ]
  },
  {
    "topicId": "verb_grammar/pronouns_こそあど",
    "title": "Pronouns: こそあど",
    "excerpt": "Pronouns:こそあど In addition to regular nouns, Japanese has a set of words which are often (but mistakenly) labelled pronouns. These are colloquially known as the 乙 そあど, and they're called this because they come as series of four, starting with こ-, そ-, あ- and ど-, to refer to (conceptually or physically) close to the speaker, close to the listener, close to neither, and as question word. To properly understand this, the concept of a personal zone is im- portant: the Japanese do not separate locations in just \"here\" and \"there'\", but actually use three levels of \"somewhereness\". Words starting with こ 78 's personal zone, words starting with そ refer to things in the listener's personal zone, and words starting with あ refer to things that are neither in the speaker's nor the listener's personal zone. Fi- nally, words starting with ど are the question words for the series, known as interrogatives",
    "examples": [
      {
        "japanese": "2.4. PRONOUNS: こそあど 77"
      },
      {
        "japanese": "tense for です，でした,at the end:じゃありませんでした(ではありませんで"
      },
      {
        "japanese": "これは本でした。",
        "english": "\"This was a book.\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 87,
    "pageEnd": 90,
    "aliases": [
      "Pronouns: こそあど",
      "これ",
      "それ",
      "あれ",
      "どれ",
      "ここ",
      "そこ",
      "あそこ",
      "どこ",
      "この",
      "その",
      "あの",
      "どの"
    ]
  },
  {
    "topicId": "verb_grammar/adjectives",
    "title": "Adjectives",
    "excerpt": "Adjectives We need to take a moment to examine verbal adjectives, and adjectives in general, because they can do something verbs cannot do, and that's to indi- cate properties.",
    "examples": [
      {
        "japanese": "past 連用形+あった(c） theoretically,未然形+なかった",
        "english": "'Theoretically' is used here, because it doesn't make a lot of sense to"
      },
      {
        "japanese": "れんたいけい"
      },
      {
        "japanese": "さかな さけまぐろ さいきんたか"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 79,
    "pageEnd": 80,
    "aliases": [
      "Adjectives",
      "い-Adjective",
      "い-Adjectives",
      "な-Adjective",
      "な-Adjectives",
      "形容詞",
      "形容動詞"
    ]
  },
  {
    "topicId": "verb_grammar/basic_inflections",
    "title": "Basic inflections",
    "excerpt": "Basic inflections Throughout the course of this section we will look at basic inflections for verbs and verbal adjectives, as well as look at a small number of parti- cles that are intricately intervowen with verb grammar.",
    "examples": [
      {
        "japanese": "adjective未然形連用形連体形已然形 (命令形)"
      },
      {
        "japanese": "高い 高く 高く 高い 高けれ (高かれ)"
      },
      {
        "japanese": "楽しい 楽しく 楽しく 楽しい 楽しけれ (楽しかれ)"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 66,
    "pageEnd": 69,
    "aliases": [
      "Basic inflections",
      "Verb (Non-past)",
      "Dictionary form",
      "う-Verb (Dictionary)",
      "る-Verb (Dictionary)",
      "Negative",
      "Negative-Past",
      "Past",
      "ます",
      "ません",
      "ました",
      "ませんでした"
    ]
  },
  {
    "topicId": "more_grammar/continuative_て_form",
    "title": "Continuative: て form",
    "excerpt": "Continuative: て form The continuative in Japanese is also commonly refered to as the \"て form', because it relies on the 連用形 of classical helper verb for completion, つ, which is て.",
    "examples": [
      {
        "japanese": "未然形 て"
      },
      {
        "japanese": "連用形 て"
      },
      {
        "japanese": "終止形 O"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 113,
    "pageEnd": 117,
    "aliases": [
      "Continuative: て form",
      "Verb て",
      "Adjective + て",
      "ている",
      "てある",
      "てしまう",
      "てみる",
      "てから",
      "なくて",
      "てよかった",
      "ちゃう",
      "ていく",
      "ていた",
      "て初めて"
    ]
  },
  {
    "topicId": "more_grammar/requesting_て_てください",
    "title": "Requesting: て, てください",
    "excerpt": "Requesting:て,てください Imperative request We already saw that we can use the verb 連用形 + てく ださい to form a request, にはいくだ コーヒーを二杯下さい。 \"Two coffee, please.\" But we can also use the plain て form to form an informal request, or plea: 待って。 \"Wait (please)\" か これを買って? \"Buy this (for me)?\" Of course, like all requests, they can be made to sound demanding, so intonation counts. If we say 待て instead of 待つて, cutting out the stop in the middle to sound curt, then rather than a request this may very well be experienced as a command instead. Similarly, saying U て in a stern tone might be less commanding than L ろ, but will still be experienced as a command more than as request. Prohibitive request This kind of requesting can of course also be done in a prohibitive manner, in which case we rely on the continuative form for ない using です, ない で: い 行かないで。 (Please) don't go. The \"please'\" is implied, and this form",
    "examples": [
      {
        "japanese": "にはいくだ"
      },
      {
        "japanese": "コーヒーを二杯下さい。",
        "english": "\"Two coffee, please.\""
      },
      {
        "japanese": "これを買って?",
        "english": "\"Buy this (for me)?\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 143,
    "pageEnd": 143,
    "aliases": [
      "Requesting: て, てください",
      "てください",
      "て下さい",
      "ください",
      "て頂戴",
      "お～願う"
    ]
  },
  {
    "topicId": "more_grammar/representative_listing_たり",
    "title": "Representative listing: たり",
    "excerpt": "Representative listing: たり If, instead of chaining, you want to only list representative actions for which order doesn't matter, such as \"Today I read my book, played some video games and walked the dog\" in which you probably did all those things a few times in no real order, then the T form is of little use.",
    "examples": [
      {
        "japanese": "寿司を食べてみませんか。",
        "english": "\"Won't (you) try eating some sushi?\""
      },
      {
        "japanese": "じてんしゃ の ぜんぜん"
      },
      {
        "japanese": "自転車を乗ってみましたが全然だめでした。",
        "english": "\" (I) tried to ride a bicycle, but that failed horribly."
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 123,
    "pageEnd": 123,
    "aliases": [
      "Representative listing: たり",
      "たり",
      "たり～たり",
      "し～し"
    ]
  },
  {
    "topicId": "more_grammar/conditional_たら_なら",
    "title": "Conditional: たら, なら",
    "excerpt": "Conditional: たら,なら In the same series of inflections that contract with 五段 verbs (, て and かていけい たり)， we find たら，which is the conditional form, or 仮定形, for た.",
    "examples": [
      {
        "japanese": "きょう がっこう い じゆぎょう で はん た"
      },
      {
        "japanese": "今日は学校に行ったり、 授業に出たり、ご飯を食べたりしました。",
        "english": "\"Today (I) went to school, went to class and ate.\""
      },
      {
        "japanese": "きのう ほん よ"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 124,
    "pageEnd": 126,
    "aliases": [
      "Conditional: たら, なら",
      "たら",
      "なら",
      "ならば",
      "もし"
    ]
  },
  {
    "topicId": "more_grammar/desire",
    "title": "Desire",
    "excerpt": "Desire First person desirative: たい Unlike the previous constructions starting with the syllable z, this inflec- tion doesn't involve a classical helper verb, but a helper adjective, fz い (which has a kanji form, 度W, but this is not used in modern Japanese).",
    "examples": [
      {
        "japanese": "未然形 たく"
      },
      {
        "japanese": "連用形 たく"
      },
      {
        "japanese": "連体形 たい"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 127,
    "pageEnd": 130,
    "aliases": [
      "Desire",
      "たい",
      "たがる",
      "ほしい",
      "欲しい",
      "がほしい",
      "のがすき",
      "好き",
      "きらい",
      "嫌い"
    ]
  },
  {
    "topicId": "more_grammar/pseudo_future_おう_よう",
    "title": "Pseudo-future: おう/よう",
    "excerpt": "Pseudo-future:おう/よう The pseudo-future is used for three things, which are called the presump- tive (\"it's probably the case that..\"), the dubitative (\"will/shall ….?\") and the cohortative (\"let's …\").",
    "examples": [
      {
        "japanese": "このドアが赤くて欲しい。",
        "english": "\"(I) want this door red.\""
      },
      {
        "japanese": "使って欲しい。"
      },
      {
        "japanese": "使って欲しいです。",
        "english": "\"(I) want it made (being said in a less direct manner than the above"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 131,
    "pageEnd": 135,
    "aliases": [
      "Pseudo-future: おう/よう",
      "ようと思う",
      "おうと思う",
      "Verb[よう]",
      "ましょう",
      "ませんか"
    ]
  },
  {
    "topicId": "more_grammar/hypothetical_えば",
    "title": "Hypothetical: えば",
    "excerpt": "Hypothetical:えば The hypothetical construction, hinted at earlier in the section on Z ら (con- いぜんけい ditional), is created by adding the particle lば to the 已然形, forming the かていけい 仮定形 or hypothetical form.",
    "examples": [
      {
        "japanese": "えいが み"
      },
      {
        "japanese": "その映画を見ようか見まいか。",
        "english": "\"Should (I) go see that movie, or not see that movie..'"
      },
      {
        "japanese": "どうしても伸びまい。",
        "english": "\"That shouldn't stretch regardless of what (you) do.'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 136,
    "pageEnd": 137,
    "aliases": [
      "Hypothetical: えば",
      "ば",
      "えば",
      "なければ",
      "ばいい"
    ]
  },
  {
    "topicId": "more_grammar/commands",
    "title": "Commands",
    "excerpt": "Commands There are two kinds of commands, namely imperative commands (things one should do) and prohibitive commands (things one should not do).",
    "examples": [
      {
        "japanese": "ハイデガーを読めば分かります。",
        "english": "\"If (you) read Heidegger, (you)'l understand."
      },
      {
        "japanese": "かね た もの か"
      },
      {
        "japanese": "お金があれば、おいしい食べ物が買えます。",
        "english": "\"If (you) have money, (you) can buy delicious food.\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 138,
    "pageEnd": 142,
    "aliases": [
      "Commands",
      "命令形",
      "な$",
      "たまえ",
      "なさい",
      "ないで",
      "そんな",
      "こんな",
      "あんな",
      "どんな"
    ]
  },
  {
    "topicId": "more_grammar/passive_れる_られる",
    "title": "Passive: れる/られる",
    "excerpt": "3.2.11 Passive:れる/られる Passive constructions are, as their name implies, constructions which de- scribe actions in a passive voice. Unlike \"I eat dinner\" or \"The cat is play- ing with the squeaky toy'\", which are in active voice, they refer to phrases like \"Dinner was eaten by me'\" or \"The squeaky toy was played with by うけみ the cat\". In Japanese, this passive voice, called 受身, is achieved through the use of the two helper verbs れる (for 五段 verbs) and られる (for 一段 verbs), which are added to a verb's 未然形. 五段verb passive 会う 会わ+れる 歩く 歩か+れる 急ぐ 急が+れる 話す 話さ+れる 死ぬ 死な+れる 学ぶ 学ば+れる 読む 読ま+れる 待つ 待た+れる 分かる 分から+れる 一段 verb passive 見る 見+られる 伸びる 伸び+られる 食べる 食べ+られる irregular passive する さ-未然形+れる，さ-未然形 +られる (される being more common) 来る こ+られる た Thus, a simple phrase like 食べます, meaning \"(I) eat\", can be made passive: 食べられます, \"(something) is being eaten (by someone)\". This change from active voice to passive voice co",
    "examples": [
      {
        "japanese": "会う 会わ+れる"
      },
      {
        "japanese": "歩く 歩か+れる"
      },
      {
        "japanese": "急ぐ 急が+れる"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 144,
    "pageEnd": 145,
    "aliases": [
      "Passive: れる/られる",
      "れる",
      "られる",
      "Passive"
    ]
  },
  {
    "topicId": "more_grammar/causative_せる_させる",
    "title": "Causative: せる/させる",
    "excerpt": "Causative:せる/させる Causative constructions are, as their name implies, constructions which indicate something was caused by someone. In English, this comes down to statements such as \"I was made to do the dishes by my mom', and in Japanese, these constructions use the verbs せる (for 五段 verbs) and させ る (for 一段 verbs). These are paired, like れる/られる with the 未然形. (さ)せる follow the 一段 scheme: bases させる せる 未然形 -させ -せ 連用形 -させ -せ 連体形 -させる -せる 已然形 -させれ -せれ 命令形-させ -せ  As mentioned, the way these two helper verbs are added is identical to the way (ら)れる is added: 五段 verb causative 会う 会わ+せる 歩く 歩か+せる 急ぐ 急が+せる 話す 話さ+せる 死ぬ 死な+せる 学ぶ 学ば+せる 読む 読ま+せる 待つ 待た+せる 分かる 分から+せる 一段verb causative 見る 見+させる 伸びる 伸び+させる 食べる 食べ+させる irregular causative する さ-未然形+せる 来る こ+させる Again, we should take note that we use the correct particles, except in this case we cannot rely on a parallel with English: the person doing the causing i",
    "examples": [
      {
        "japanese": "だれ おとうと じてんしゃ ぬす"
      },
      {
        "japanese": "誰かが弟の自転車を盗みました。",
        "english": "active, \"Someone stole my (younger) brother's bicycle.\""
      },
      {
        "japanese": "誰かに弟の自転車が盗まれた。",
        "english": "passive, \"My brother was bestolen of his bike by someone.'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 146,
    "pageEnd": 147,
    "aliases": [
      "Causative: せる/させる",
      "せる",
      "させる",
      "Causative"
    ]
  },
  {
    "topicId": "more_grammar/causative_passive_せられる_させられる",
    "title": "Causative passive: せられる/させられる",
    "excerpt": "Causative passive:せられる/させられる The title sounds like a combination of the causative and the passive, and that's essentially what it is. It's long, and its use is not rare. In English, this form reads \"have been made to do …..\" and is also quite long. So, just like in most western language, the more nuance you want to place in your verb conjugation, the longer it'll get. However, because this is a passive, we must make sure to use par- ticles accordingly: こども かあ あさ はん た 子供たちがお母さんに朝ご飯を食べさせられました。 \"The children were made to eat breakfast by their mother.' せんせい しゅくだい なお 先生に宿題をやり直させられました。 \" (I) had been made to redo (my) homework by (the) teacher.\" 3.2.14 Potential Long potential: られる As mentioned in the section on the passive, one of the other roles that れ る/ら れる can play is that of the (long) potential. The potential form of a verb in English is typically constructed using the auxiliary verb \"",
    "examples": [
      {
        "japanese": "しゃちょう う"
      },
      {
        "japanese": "社長にプロジェクトを受けさせました。",
        "english": "\"The CEO let me take on (the) project.'"
      },
      {
        "japanese": "こども かあ あさ はん た"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 148,
    "pageEnd": 148,
    "aliases": [
      "Causative passive: せられる/させられる",
      "せられる",
      "させられる",
      "Causative-Passive"
    ]
  },
  {
    "topicId": "more_grammar/potential",
    "title": "Potential",
    "excerpt": "Potential Long potential: られる As mentioned in the section on the passive, one of the other roles that れ る/ら れる can play is that of the (long) potential.",
    "examples": [
      {
        "japanese": "しゃちょう う"
      },
      {
        "japanese": "社長にプロジェクトを受けさせました。",
        "english": "\"The CEO let me take on (the) project.'"
      },
      {
        "japanese": "こども かあ あさ はん た"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 148,
    "pageEnd": 151,
    "aliases": [
      "Potential",
      "ことができる",
      "できる",
      "得る",
      "づらい",
      "ぎみ",
      "切る",
      "抜く",
      "聞こえる",
      "見える"
    ]
  },
  {
    "topicId": "more_grammar/formality_humble_honorific_speech_patterns",
    "title": "Formality: humble/honorific speech patterns",
    "excerpt": "Formality: humble/honorific speech patterns In addition to being polite, in formal Japanese, a dreadfully important as- けんじよう そんけい pect is to use the right mix of humble (謙譲) and honorific (尊敬) speech patterns.",
    "examples": [
      {
        "japanese": "見られません。"
      },
      {
        "japanese": "見ることが出来ません。",
        "english": "We would have good reason to apologise for telling them to look at"
      },
      {
        "japanese": "けんじよう そんけい"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 152,
    "pageEnd": 152,
    "aliases": [
      "Formality: humble/honorific speech patterns",
      "お～になる",
      "いらっしゃる",
      "なさる",
      "いたす",
      "ございます",
      "でございます"
    ]
  },
  {
    "topicId": "particles/essential_particles",
    "title": "Essential particles",
    "excerpt": "essential particles, the second and third covering less frequently and even several 'rare' particles and particle combinations. 4.2.1 Essential particles The essential particle list consists of the particles か, が, と, で, こ, の, は, も and を (as well as ~, which is not essential but belongs in this list because of the way it contrasts with a particular use of lC). Traditionally, て would be considered part of this list, but we already extensively covered T in the verb section on the て form. The particles in this section are considered \"essential\", because they cover the absolute minimum of grammatical roles that you need to un- derstand before you understand Japanese at a basic conversational level. While the list seems short, a mere 10 particles, most of these particles — in terms of what you might be used to from English – do many different things. While there is typically some unifying conc",
    "examples": [
      {
        "japanese": "行きます。"
      },
      {
        "japanese": "行きますか。"
      },
      {
        "japanese": "しようかと思った。",
        "english": "\"'(I) thought (about) whether I should do (it).\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 165,
    "pageEnd": 187,
    "aliases": [
      "Essential particles",
      "は",
      "が",
      "も",
      "の",
      "か",
      "を",
      "で",
      "に",
      "へ",
      "と",
      "や",
      "ね",
      "よ",
      "から",
      "まで",
      "ごろ"
    ]
  },
  {
    "topicId": "particles/emphatic_particles",
    "title": "Emphatic particles",
    "excerpt": "emphatic particles, and the second focussing on more general grammatical particles. 4.3.1 Emphatic particles よ - Informative, emphatic This particle is most often found at the end of statements, where it marks information as being either new information, or contrary to the listener's belief. While tempting, this particle should not be translated with an ex- clamation mark, as よ isn't actually an exclamation, but only emphasises the \"new information'\"/\"contrary information' aspect. For instance: すご おもしろ 凄く面白かった。 \"(It) was very fun.' 凄く面白かったよ。 \"(It) was very fun (you didn't know or expect this, so I'm telling you it was).\" When よ is used to emphasise contrasting information, the situation is usually some kind of misunderstanding: ちが あたら ふる 違うよ。新しいのはここ、古いのはあそこだよ。 \"No (emphatic). The new ones (go) here, the old ones (go) over there (emphatic).\" While it would be temping in this use to transl",
    "examples": [
      {
        "japanese": "すご おもしろ"
      },
      {
        "japanese": "凄く面白かった。",
        "english": "\"(It) was very fun.'"
      },
      {
        "japanese": "凄く面白かったよ。",
        "english": "\"(It) was very fun (you didn't know or expect this, so I'm telling you"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 188,
    "pageEnd": 193,
    "aliases": [
      "Emphatic particles",
      "しか",
      "ばかり",
      "だけ",
      "こそ",
      "さえ",
      "でも",
      "くらい",
      "ほど",
      "など"
    ]
  },
  {
    "topicId": "particles/further_particles",
    "title": "Further particles",
    "excerpt": "Further particles のです,んです,のだ,んだ-Reasoning A combination of the genitive の, permissibly contracted to h, and the copula, this \"particle\" – or rather, set of particles – can be used as a way to give a reason for something without explicitly stating so.",
    "examples": [
      {
        "japanese": "のです,んです,のだ,んだ-Reasoning"
      },
      {
        "japanese": "A:眠そうね。"
      },
      {
        "japanese": "B:ああ。電車で眠ってしまったんだ。"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 194,
    "pageEnd": 213,
    "aliases": [
      "Further particles",
      "について",
      "として",
      "において",
      "に関して",
      "に対して",
      "によって",
      "につれて",
      "にしたがって",
      "にとって",
      "に取って",
      "から見ると",
      "から言うと",
      "上",
      "以上",
      "反面",
      "限り",
      "向き",
      "向け"
    ]
  },
  {
    "topicId": "counters_and_counting/counting",
    "title": "Counting",
    "excerpt": "5.1 Counting Before we look at the counter particles, let's briefly look at counting it- self. In the outline on Japanese, I mentioned three different ways to count from one to ten, and this comes from the fact that Japan, while it borrowed the Chinese kanji and readings, also had its own language prior to know- ing anything about China. Not surprisingly then, counting was done with completely different words in pre-China Japan. However, unlike this pre- China native Japanese counting system, the Chinese derived series for one through ten is reasonably simple: number written and pronounced いち 1 壱in formal writing. に 2 二, 弐 in formal writing. さん 3 三,参 in formal writing. 4 四– in the \"normal\" counting series, this number can be pronounced よh, a native Japanese reading. ご五 5 K八 6 しち 7 七 – like for four, in the \"normal\" counting series this number can be pronounced なな, also a native Japanese",
    "examples": [
      {
        "japanese": "120= 100+2×10=百二十"
      },
      {
        "japanese": "780=7×100+8×10=七百八十"
      },
      {
        "japanese": "1300= 1000+3×100=千三百"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 238,
    "pageEnd": 241,
    "aliases": [
      "Counting",
      "Number",
      "なん + counter",
      "一つ",
      "二つ",
      "いくつ"
    ]
  },
  {
    "topicId": "counters_and_counting/counters",
    "title": "Counters",
    "excerpt": "Counters As mentioned, counters can be split into specific and general counter cat- egories. Specific counters are for instance unit counters such as for time or distance, and general counters are used for categorical items such as 'bound objects' or 'pieces of [somethingl'. Rather than just using these two categories, we also include a list of common numerical orders, which act as counters too. This list is followed by the counters split up into four cat- egories: general article counters, counters for living things, counters for occurrences, and time related unit counters. In addition to counters, a list of adverbs used for quantification is included in this chapter. While strictly speaking these are not counters, they are used when you need to quantify actions without being able to rely on a counter (such as \"I read books often', where a numerical statement is impossible to give). 5.2",
    "examples": [
      {
        "japanese": "百 (一百) 二百 三百 四百 五百"
      },
      {
        "japanese": "ひゃく（いっぴゃく）にひゃくさんびゃく。 よんひゃく ごひゃく"
      },
      {
        "japanese": "六百 七百 八百 九百 何百"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 245,
    "pageEnd": 245,
    "aliases": [
      "Counters",
      "counter",
      "枚",
      "冊",
      "本",
      "人"
    ]
  },
  {
    "topicId": "counters_and_counting/counting_time_related_units",
    "title": "Counting time related units",
    "excerpt": "Counting time related units びよう 秒 - Seconds Counting seconds in Japanese uses 秒, for which the pronunciations are: 一秒 二秒 三秒 四秒 五秒 六秒 いちびょう にびょう さんびょう よんびょう ごびょう ろくびょう 七秒 八秒 九秒 十秒 何秒 ななびょう はちびょう くびょう じゅうびょう なんびょう (きゅうびょう) An example sentence would be: はんぷ 何秒かかりますか。二十秒か、半分か。",
    "examples": [
      {
        "japanese": "一秒 二秒 三秒 四秒 五秒 六秒"
      },
      {
        "japanese": "いちびょう にびょう さんびょう よんびょう ごびょう ろくびょう"
      },
      {
        "japanese": "七秒 八秒 九秒 十秒 何秒"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 261,
    "pageEnd": 268,
    "aliases": [
      "Counting time related units",
      "時間",
      "日",
      "週間",
      "か月",
      "年",
      "分"
    ]
  },
  {
    "topicId": "language_patterns/comparisons_preferences_and_choice",
    "title": "Comparisons, preferences and choice",
    "excerpt": "Comparisons, preferences and choice Comparing and choosing are two very related subjects. Making a choice is essentially the same as making a subjective comparison, where one thing is more favourable than the other. This concept is quite obvious in Japanese, where we encounter two types of choices: the binary choice, and the open choice. 6.1.1 Binary choices The binary choice is simply a choice between two things. One's preference can swing one way or the other, or one can indicate that either choice is fine, or both are to be rejected. This binary choice concept in Japanese uses 273",
    "examples": [],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 283,
    "pageEnd": 283,
    "aliases": [
      "Comparisons, preferences and choice",
      "より",
      "のほうが",
      "どちら",
      "どっち",
      "あまり"
    ]
  },
  {
    "topicId": "language_patterns/binary_choices",
    "title": "Binary choices",
    "excerpt": "Binary choices The binary choice is simply a choice between two things. One's preference can swing one way or the other, or one can indicate that either choice is fine, or both are to be rejected. This binary choice concept in Japanese uses 273 274 ほう the word 方, literally \"direction'\", in the following questioning pattern: xと[Y]と[どちら/どっち]の方が[some judgement call]ですか。 \"Which is (more) [something]: X, or Y?\" Note that this uses a two-item inclusive list, with either two と par- ticles, or a comma after the second choice item (though typically commas are avoided). Because of the use of どちらの方 or どっちの方 (the first being more formal than the second) this pattern literally asks \"A and B; which direction is [more] [something]?\" and can be applied to virtually anything: す バーガーとチキンサンドとどちらの方が好きですか。 \"Which do (you) like best, hamburgers or chicken sandwiches?\" でんしゃ はや 電車とバスとどちらの方が速いですか。 \"Which is fast",
    "examples": [
      {
        "japanese": "xと[Y]と[どちら/どっち]の方が[some judgement call]ですか。"
      },
      {
        "japanese": "バーガーとチキンサンドとどちらの方が好きですか。",
        "english": "\"Which do (you) like best, hamburgers or chicken sandwiches?\""
      },
      {
        "japanese": "でんしゃ はや"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 283,
    "pageEnd": 284,
    "aliases": [
      "Binary choices",
      "かどうか"
    ]
  },
  {
    "topicId": "language_patterns/comparison_through_likeness_and_impressions",
    "title": "Comparison through likeness, and impressions",
    "excerpt": "6.1.3 Comparison through likeness, and impressions Closely related to choices is the concept of comparing things. After all, if you cannot make comparisons, you cannot determine preference. There are quite a number of ways in which to compare things in Japanese, with varying degree of strength in the comparison, and varying nuance in the exact way the likeness, or contrast, works. You have already seen some よう ways in which to do this, such as そう and 様 in the verb and particles sections, but there are quite a few more, which will now look at. れんようけい ごかん れんたいけい そう- Weak impression (連用形，語干)， second hand information (連体形) The noun adjective そう (a こそあど word) paired with a verb in 連用形 or a verbal adjective's stem, is used to create the construction of \"appearing to be (at the point of) ….\" or \"seems to be … (to the speaker)\": しごと でき 仕事が出来そうですね。 \"It looks like (you)ll be able to perform this j",
    "examples": [
      {
        "japanese": "れんようけい ごかん れんたいけい"
      },
      {
        "japanese": "しごと でき"
      },
      {
        "japanese": "仕事が出来そうですね。",
        "english": "\"It looks like (you)ll be able to perform this job.\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 286,
    "pageEnd": 292,
    "aliases": [
      "Comparison through likeness, and impressions",
      "ように",
      "ような",
      "みたい",
      "らしい",
      "そうだ",
      "そうです",
      "そうに",
      "そうな",
      "あげく",
      "風"
    ]
  },
  {
    "topicId": "language_patterns/discussing_possibilities",
    "title": "Discussing possibilities",
    "excerpt": "Discussing possibilities Related to choices, comparisons and likeness, there is the subject of possi- bilities. In English, we can indicate possibility in a variety of ways; things \"may\" or \"might\", things \"can', or \"could\" be, they're possible, likely, un- likely, or even \"stand a chance to be'\". In Japanese, too, there are a number of useful ways to describe possibilities, which we shall look at in this sec- tion. かも知れない- Might or might not The first, and probably most used, is the construction かも 知れない. This construction technically consists of the particles 为 and も, followed by the negative short potential of 知る, to know, or be informed; 知れない.'This construction translates to \"it could be that ….\", implying that the speaker doesn't actually know, but is not ruling out that something could be the case. い い A：行かないと言っただろう。 B:まあ、そう言ったかもしれません。 A: \"Didn't he say he wasn't coming?\" B: \"He mig",
    "examples": [
      {
        "japanese": "A：行かないと言っただろう。"
      },
      {
        "japanese": "B:まあ、そう言ったかもしれません。",
        "english": "A: \"Didn't he say he wasn't coming?\""
      },
      {
        "japanese": "A：石田さん、めがね落としたか。"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 293,
    "pageEnd": 294,
    "aliases": [
      "Discussing possibilities",
      "かもしれない",
      "でしょう",
      "だろう"
    ]
  },
  {
    "topicId": "language_patterns/nominalising",
    "title": "Nominalising",
    "excerpt": "Nominalising Nominalisers are those words that turn (arbitrary) words or phrases into noun phrases, so that they can be used in larger sentences as topics, sub- jects, direct objects or what have you.",
    "examples": [
      {
        "japanese": "[X]かどうか分かりません:"
      },
      {
        "japanese": "ことし お わ"
      },
      {
        "japanese": "今年は落とすかどうか分かりません。",
        "english": "\"I don't know whether or not I'll make this year's grade.'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 295,
    "pageEnd": 295,
    "aliases": [
      "Nominalising",
      "こと",
      "のこと",
      "ことがある",
      "たことがある"
    ]
  },
  {
    "topicId": "language_patterns/back_referral_using_の",
    "title": "Back referral using の",
    "excerpt": "6.2.1 Back referral using の The simplest nominaliser is just the nominalising の. This turns any clause that precedes it into a back referral to something either previously men- tioned, or previously established as topic somehow. Say we have the fol- lowing sentence: びじゅつかん み ( 美術館を見に行く。 \"Going to an art gallery.' We can nominalise this sentence into a back referral using の by ap- pending it to this sentence: 美術館を見に行くの This has no direct translation on its own, but requires a bigger con- text to operate in; on its own it can mean anything that can be approxi- mated with \"the [going to the art gallery]\". Only when used in a bigger sentence will this noun clause really make sense: たの 美術館を見に行くのが楽しかった。 \"Going to (the) art gallery (today) was fun. Here, the noun phrase has been turned into a back referral to some- thing that happened. こと 6.2.2 Abstract conceptualisation using 事 The noun こ と is",
    "examples": [
      {
        "japanese": "びじゅつかん み ("
      },
      {
        "japanese": "美術館を見に行く。",
        "english": "\"Going to an art gallery.'"
      },
      {
        "japanese": "美術館を見に行くの",
        "english": "This has no direct translation on its own, but requires a bigger con-"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 296,
    "pageEnd": 296,
    "aliases": [
      "Back referral using の",
      "のです",
      "んです",
      "のだ",
      "んだ"
    ]
  },
  {
    "topicId": "language_patterns/abstract_conceptualisation_using_こと_事",
    "title": "Abstract conceptualisation using こと (事)",
    "excerpt": "6.2.1 Back referral using の The simplest nominaliser is just the nominalising の. This turns any clause that precedes it into a back referral to something either previously men- tioned, or previously established as topic somehow. Say we have the fol- lowing sentence: びじゅつかん み ( 美術館を見に行く。 \"Going to an art gallery.' We can nominalise this sentence into a back referral using の by ap- pending it to this sentence: 美術館を見に行くの This has no direct translation on its own, but requires a bigger con- text to operate in; on its own it can mean anything that can be approxi- mated with \"the [going to the art gallery]\". Only when used in a bigger sentence will this noun clause really make sense: たの 美術館を見に行くのが楽しかった。 \"Going to (the) art gallery (today) was fun. Here, the noun phrase has been turned into a back referral to some- thing that happened. こと 6.2.2 Abstract conceptualisation using 事 The noun こ と is",
    "examples": [
      {
        "japanese": "びじゅつかん み ("
      },
      {
        "japanese": "美術館を見に行く。",
        "english": "\"Going to an art gallery.'"
      },
      {
        "japanese": "美術館を見に行くの",
        "english": "This has no direct translation on its own, but requires a bigger con-"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 296,
    "pageEnd": 296,
    "aliases": [
      "Abstract conceptualisation using こと (事)",
      "ことだ",
      "ことなく"
    ]
  },
  {
    "topicId": "language_patterns/indicating_a_specific_time_or_event_using_とき_時",
    "title": "Indicating a specific time or event using とき (時)",
    "excerpt": "たび 6.2.6 Describing an occurrence using 度 If you want to describe something that occurs or can occur at times, then z び lets you say something general about these occurrences.",
    "examples": [
      {
        "japanese": "ほしぞら み よる おも だ"
      },
      {
        "japanese": "星空を見るたびに、あの夜のことを思い出す。",
        "english": "\"Whenever (I) look up at a starry sky, (I) remember that (special)"
      },
      {
        "japanese": "はじ にほん き じゅうはっさい"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 300,
    "pageEnd": 300,
    "aliases": [
      "Indicating a specific time or event using とき (時)",
      "とき",
      "時"
    ]
  },
  {
    "topicId": "language_patterns/stating_an_expectation_using_はず_筈",
    "title": "Stating an expectation using はず (筈)",
    "excerpt": "はず 6.2.89 Stating an expectation using 筈 In English, which is the language this book is written in, there are two interpretations possible for \"should\": it can mean \"must'\" such as in \"you should clean up your room', and it can mean \"expect\", such as in \"she should be showing up any minute now'\".",
    "examples": [
      {
        "japanese": "今日はみんなが来るはずなんだ。",
        "english": "literally: \"It should be that everyone will come today."
      },
      {
        "japanese": "未然形 べから べから べから"
      },
      {
        "japanese": "連用形 べく べかり べく"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 301,
    "pageEnd": 301,
    "aliases": [
      "Stating an expectation using はず (筈)",
      "はず"
    ]
  },
  {
    "topicId": "language_patterns/stating_a_social_expectation_or_custom_using_べき",
    "title": "Stating a social expectation or custom using べき",
    "excerpt": "Stating a social expectation or custom using べき Where はず is used to indicate the expecting \"should\", べき is used to indi- cate the somewhat imperative \"should\".",
    "examples": [
      {
        "japanese": "今日はみんなが来るはずなんだ。",
        "english": "literally: \"It should be that everyone will come today."
      },
      {
        "japanese": "未然形 べから べから べから"
      },
      {
        "japanese": "連用形 べく べかり べく"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 301,
    "pageEnd": 301,
    "aliases": [
      "Stating a social expectation or custom using べき",
      "べき"
    ]
  },
  {
    "topicId": "language_patterns/indicating_a_moment_in_time_using_ところ_所",
    "title": "Indicating a moment in time using ところ(所)",
    "excerpt": ": きみ せきにん とる 君が責任を取るべきだったのだ。 \"You should have taken responsibility. Here the clause 責任を取る， \"to take responsibility', is illustrated as being something that is socially expected from someone in whichever con- text this phrase was said in. Sometimes this social expectation is a given, or common sense, but sometimes the expectation is very context dependent, such as: まじめ えいご べんきょう 真面目に英語を勉強すべきです。 '(You) should study English seriously.' Here the clause 真面目に英語を勉強する，\"to study English se- riously\", is turned into a social expectation because of the behaviour of whoever it is said to right now. Probably, they are goofing off, while a \"proper\" person would be studying hard in order to meet the social stan- dards. This sentence also shows a special contraction when using ベき with する, in that it turns into すべき instead of するべき as expected. Truly, there is nothing simple, or ordinary, about this word.",
    "examples": [
      {
        "japanese": "きみ せきにん とる"
      },
      {
        "japanese": "君が責任を取るべきだったのだ。",
        "english": "\"You should have taken responsibility."
      },
      {
        "japanese": "まじめ えいご べんきょう"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 302,
    "pageEnd": 302,
    "aliases": [
      "Indicating a moment in time using ところ(所)",
      "ところ",
      "ところで",
      "ところが",
      "ところに",
      "きり"
    ]
  },
  {
    "topicId": "language_patterns/stating_an_intention_using_つ_積_もり",
    "title": "Stating an intention using つ (積)もり",
    "excerpt": "つ 6.2.11 Stating an intention using 積もり Derived from the verb 積も る，\"to intend\", the nominaliser つも り turns a 連体形 clause into an intention: きょう わかやま い 今日和歌山まで行くつもりだ。",
    "examples": [
      {
        "japanese": "きょう わかやま い"
      },
      {
        "japanese": "今日和歌山まで行くつもりだ。",
        "english": "\"(We) intend to go up to Wakayama today."
      },
      {
        "japanese": "かれいっしょうけんめいはたら"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 303,
    "pageEnd": 303,
    "aliases": [
      "Stating an intention using つ (積)もり",
      "つもり"
    ]
  },
  {
    "topicId": "language_patterns/stating_a_meaning_or_situational_explanation_using_わけ_訳",
    "title": "Stating a meaning or situational explanation using わけ (訳)",
    "excerpt": "つ 6.2.11 Stating an intention using 積もり Derived from the verb 積も る，\"to intend\", the nominaliser つも り turns a 連体形 clause into an intention: きょう わかやま い 今日和歌山まで行くつもりだ。",
    "examples": [
      {
        "japanese": "きょう わかやま い"
      },
      {
        "japanese": "今日和歌山まで行くつもりだ。",
        "english": "\"(We) intend to go up to Wakayama today."
      },
      {
        "japanese": "かれいっしょうけんめいはたら"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 303,
    "pageEnd": 304,
    "aliases": [
      "Stating a meaning or situational explanation using わけ (訳)",
      "わけ",
      "わけではない"
    ]
  },
  {
    "topicId": "language_patterns/describing_a_way_using_よう_様",
    "title": "Describing a way, using よう (様)",
    "excerpt": "よう 6.2.13 I Describing a way, using g様 We already dealt with よ う in the section on comparison and likeness, in which we also touched on the subject that it can be used to indicate ways れんたいけい in which things need to be done.",
    "examples": [
      {
        "japanese": "れんたいけい"
      },
      {
        "japanese": "きようかしよ も い くだ"
      },
      {
        "japanese": "教科書を持ってくるように言って下さい。",
        "english": "\"Please tell (her) to bring (her) textbook.'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 305,
    "pageEnd": 305,
    "aliases": [
      "Describing a way, using よう (様)",
      "ようにする",
      "ようがない"
    ]
  },
  {
    "topicId": "language_patterns/indicating_an_exact_manner_using_まま",
    "title": "Indicating an exact manner using まま",
    "excerpt": "Indicating an exact manner using まま Unlike よう，まま actually specifies an exact manner in which actions take place. ま ま takes a clause and specifies that what follows occurs in the exact",
    "examples": [
      {
        "japanese": "れんたいけい"
      },
      {
        "japanese": "きようかしよ も い くだ"
      },
      {
        "japanese": "教科書を持ってくるように言って下さい。",
        "english": "\"Please tell (her) to bring (her) textbook.'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 305,
    "pageEnd": 305,
    "aliases": [
      "Indicating an exact manner using まま",
      "まま"
    ]
  },
  {
    "topicId": "language_patterns/stating_purpose_using_ため_為",
    "title": "Stating purpose using ため (為)",
    "excerpt": ". This can be done for noun phrases as follows: つづ くだ そのまま続いて下さい。 \"Please continue like that.' Or it can be applied to 連体形 verb phrases: い とど かれ き 行くか留まるか彼の決めるままにさせよう。 \"(We)'l let him go or stay as he decides to.' In this sentence, 決める, \"to decide\" is turned into an exact way, and linked to \"him\" (彼), to create \"the way he decides (on)\",彼の決めるまま. Note that while 決まる is a verb, 決めるまま is, by the very role of まま as nominaliser, a noun phrase, and thus can be used in a genitive の linking. ぼうし きょうしつ はい 帽子をかぶったままで教室に入るべきじゃない。 \"(One) shouldn't enter the classroom while wearing (their) hat/cap.' The literal (though rather ungrammatical) translation of this sen- tence would be \"in the manner of wearing one's cap, it is not the social thing to enter a classroom\". ため 6.2.15 Stating purpose using 為 When stating the purpose of a particular action, fz め is used. This nomi- naliser takes a clause and li",
    "examples": [
      {
        "japanese": "つづ くだ"
      },
      {
        "japanese": "そのまま続いて下さい。",
        "english": "\"Please continue like that.'"
      },
      {
        "japanese": "い とど かれ き"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 306,
    "pageEnd": 306,
    "aliases": [
      "Stating purpose using ため (為)",
      "ため",
      "ために",
      "ための"
    ]
  },
  {
    "topicId": "language_patterns/talking_about_a_something_using_とい_言_う",
    "title": "Talking about a 'something' using とい (言)う",
    "excerpt": "まね 6.2.161 Incidating apparent behaviour using 真似 まね literally means immitation, and it is typically used to indicate appar- ent (and insincere) behaviour.",
    "examples": [
      {
        "japanese": "おとな まね"
      },
      {
        "japanese": "大人の真似はやめるよ。",
        "english": "'Stop acting like an adult."
      },
      {
        "japanese": "かのじよ な"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 307,
    "pageEnd": 307,
    "aliases": [
      "Talking about a 'something' using とい (言)う",
      "という",
      "って",
      "といった",
      "とか",
      "いわゆる",
      "そういう"
    ]
  },
  {
    "topicId": "language_patterns/giving_and_receiving",
    "title": "Giving and receiving",
    "excerpt": "Giving and receiving Giving, or doing something for someone, and receiving, or taking a lib- erty (ie, helping oneself to something) are concepts that seem simple if 308 're used to the English way of expressing yourself, but in Japanese, these seemingly trivial things require quite a bit of explanation, as they are dependent on relative social status, direction of giving or receiving, as well as involving a careful choice in particles to use.",
    "examples": [
      {
        "japanese": "用形+て+)上げる is used."
      },
      {
        "japanese": "形+て+)差し上げるis used.",
        "english": "Now, this requires a bit more explaining because when it comes to giving,"
      },
      {
        "japanese": "ぜんぜん知らない人に何々を上げました。",
        "english": "\"I gave something-or-other to a person I don't know in the slightest.'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 317,
    "pageEnd": 325,
    "aliases": [
      "Giving and receiving",
      "てあげる",
      "てくれる",
      "てもらう",
      "あげる",
      "くれる",
      "もらう"
    ]
  },
  {
    "topicId": "language_patterns/indirect_speech",
    "title": "Indirect speech",
    "excerpt": "6.4.21 Indirect speech One of the important things in using Japanese is to be indirect whenever possible in formal situations. This entails asking indirect questions instead of direct questions, making indirect suggestions instead of telling people what they should do according to you, and stating assumptions rather than stating truths, even if they are truths. This section will explain how to turn direct speech into indirect speech, and for which constructions this is easily done. Expressing hearsay One way to state something indirectly is by making explicit the fact that you only heard or read something somewhere, rather than being some- thing you yourself believe or know. As mentioned in the section on com- parison and likeness, this is done using the noun adjective そう, in combi- nation with a clause in 連体形, to form a hear-say construction. Compare the following two statements: にんき かい",
    "examples": [
      {
        "japanese": "にんき かいさん"
      },
      {
        "japanese": "あの人気なグループが解散する。",
        "english": "\"That popular group will disband.'"
      },
      {
        "japanese": "あの人気なグループが解散するそうだ。",
        "english": "\"I hear that popular group will disband.\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "direct",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 326,
    "pageEnd": 330,
    "aliases": [
      "Indirect speech",
      "と言う",
      "と思う",
      "と考える",
      "とされている",
      "と考えられている"
    ]
  },
  {
    "topicId": "the_syntax/adverbs",
    "title": "Adverbs",
    "excerpt": "Adverbs Using words to be specific about verbs and verb actions is called using them adverbially. In fact, in that sentence the word \"adverbially'\" is an",
    "examples": [],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 45,
    "pageEnd": 45,
    "aliases": [
      "Adverbs",
      "いきなり",
      "おそらく",
      "けっこう",
      "せめて",
      "ぜんぜん",
      "たくさん",
      "たちまち",
      "つまり",
      "どうして",
      "どうせ",
      "どんどん",
      "なお",
      "なぜ",
      "まず",
      "また",
      "一応",
      "一旦",
      "何しろ",
      "精々"
    ]
  },
  {
    "topicId": "more_grammar/more_negatives",
    "title": "More negatives",
    "excerpt": "3.1.5 More negatives The basic negative form was already discussed in the previous chapter, but it only covered one of the two plain negative forms, and didn't cover polite negative forms at all.",
    "examples": [
      {
        "japanese": "連用形 ず"
      },
      {
        "japanese": "連体形 ん(ぬ)"
      },
      {
        "japanese": "已然形 ね"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 104,
    "pageEnd": 104,
    "aliases": [
      "More negatives",
      "ざる",
      "ぬ",
      "まい"
    ]
  },
  {
    "topicId": "the_syntax/verbs",
    "title": "Verbs",
    "excerpt": "Verbs Verbs are words that represent an action either taking place or being per- formed, and can be modified to show things like negatives or past tense.",
    "examples": [],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 41,
    "pageEnd": 41,
    "aliases": [
      "Verbs",
      "他動詞・自動詞",
      "自動詞",
      "他動詞",
      "おわる",
      "つづける"
    ]
  },
  {
    "topicId": "the_syntax/nouns",
    "title": "Nouns",
    "excerpt": "Nouns Nouns are words that are used to name \"something's, although those somethings don't need to be things you can actually hold in your hand and look at: \"car\", \"New York\", \"magnification\" and \"ambiguity\" are all nouns, but while you can touch a car, or point at New York, it's impossible to point at something and go \"that is magnification'\" or \"that is ambiguity\".",
    "examples": [
      {
        "japanese": "じどうし たどうし"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 42,
    "pageEnd": 42,
    "aliases": [
      "Nouns",
      "ら",
      "代",
      "中",
      "気"
    ]
  },
  {
    "topicId": "the_syntax/pronouns",
    "title": "Pronouns",
    "excerpt": "Pronouns There is a special class of words in English that act as if they're nouns, but are used to replace nouns in sentences. The best known pronoun in the English language is the word \"it\", but words like \"this\", \"that\" as well as \"you\" or \"we'\" are all examples of pronouns. Rather than constantly",
    "examples": [],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 43,
    "pageEnd": 43,
    "aliases": [
      "Pronouns",
      "誰"
    ]
  },
  {
    "topicId": "the_syntax/prefixes",
    "title": "Prefixes",
    "excerpt": "Prefixes Some particles, as well as some common concept markers, are prefixes rather than suffixes – they are placed in front of words belonging to certain",
    "examples": [],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 46,
    "pageEnd": 46,
    "aliases": [
      "Prefixes",
      "各",
      "真"
    ]
  },
  {
    "topicId": "more_grammar/conjunctive",
    "title": "Conjunctive",
    "excerpt": "Conjunctive Conjunctives are words, or constructions, which join up two different phrases. For instance, in the English sentence \"The birds are singing, the flowers are blooming; spring had arrived properly', the comma between'the birds are singing' and 'the flowers are blooming' acts as a conjunctive, as does the semi-colon between 'the flowers are bloomng' and 'spring had arrived'. In Japanese, this particular kind of conjunction can be done in a remarkably simple way: each sentence that is to be \"conjoined\" with the next has its final verb put in 連用形, and we're done: とり な 鳥が鳴く。 \" (The) birds sing.' はな さ 花が咲く。 \"(The) flowers bloom.' はる き 春が来た。 'Spring has arrived.\" If we change the final verbs in the first two sentence fom 連体形 to 連用形, then we can join them up to form the translation for our original  English sentence: 鳥が鳴き花が咲き春が来た。 \"(The) birds are singing, (the) flowers are blooming;",
    "examples": [
      {
        "japanese": "present plain 連体形 し-未然形 +ない"
      },
      {
        "japanese": "polite 連用形+ます 連用形+ません"
      },
      {
        "japanese": "past plain 連用形+た し-未然形+なかった"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 108,
    "pageEnd": 112,
    "aliases": [
      "Conjunctive",
      "つつ",
      "っぱなし"
    ]
  },
  {
    "topicId": "language_patterns/open_choices",
    "title": "Open choices",
    "excerpt": "Open choices If you want to have a larger collection of items to choose from, or you want to ask a categorical choice, then 方 cannot be used. Instead, a choice pattern なか involving ….. の 中で, meaning \"from amongst ….\" must be used. This pat- tern can be used for anything, such as specific lists of items, or just categor- ical nouns asking the person who is offered the choice to pick something that falls into the category. For instance: おんがく なに A：音楽の中で何が好きですか。 B:そうですね。ジャズが好きです。 A: \"Music-wise, what do you like?\" (literally: \"from music, what do you like?\") B: \"Hmm. I like Jazz.' This is an example of a categorical choice where the respondent ac- tually gives a specific answer. Questions like \"What food do you like\", \"which cars are fast\" fit this pattern. There is an exception to using this pattern which involves open choices for locations, such as \"Which cities in Europe have you been to\"",
    "examples": [
      {
        "japanese": "おんがく なに"
      },
      {
        "japanese": "A：音楽の中で何が好きですか。"
      },
      {
        "japanese": "B:そうですね。ジャズが好きです。",
        "english": "A: \"Music-wise, what do you like?\" (literally: \"from music, what do"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 285,
    "pageEnd": 285,
    "aliases": [
      "Open choices",
      "か何か",
      "なり",
      "やら",
      "とか",
      "など"
    ]
  },
  {
    "topicId": "language_patterns/real_conceptualisation_using_もの_物",
    "title": "Real conceptualisation using もの (物)",
    "excerpt": "Another example of the use of こ と can be seen in the following example: わたし なに くわ 私の言った事に何か付け加える事はありませんか。 \"Would (you) like to add anything to what (I)'ve said?\" In this sentence, there are two abstractions going on: one is the ab- straction of 言つた,\"said\"to 言った事，\"the thing that was said\"， and the second from 付け加える， \"to add\"(a compound verb coming from 付ける, \"to attach\", and 加える，\"to add\") to 付け加える事, \"[a] thing to add\". It should be noted that these are genuine abstractions; 言っ たこと does not only refer to the actually spoken words, but also the thoughts that they stood for, and 付lけ加え る likewise stands not just for words, but for thoughts that can be added to the already existent thoughts on whatever was being discussed. This plain past tense + 事 is also used to ask whether or not someone has experience with something, in the pattern [plain past tense+ことがある: フランスに行ったことがありますか。 \"Have (you) ever",
    "examples": [
      {
        "japanese": "わたし なに くわ"
      },
      {
        "japanese": "私の言った事に何か付け加える事はありませんか。",
        "english": "\"Would (you) like to add anything to what (I)'ve said?\""
      },
      {
        "japanese": "tense+ことがある:"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 297,
    "pageEnd": 297,
    "aliases": [
      "Real conceptualisation using もの (物)",
      "もの",
      "もん"
    ]
  },
  {
    "topicId": "language_patterns/illustrating_a_circumstance_case_or_occasion_using_ばあい_場合",
    "title": "Illustrating a circumstance, case or occasion using ばあい (場合)",
    "excerpt": "\"that which is 'being able to keep a secret secret'\". This is different from an abstraction using こと: 秘密を隠しておけること \"The concept 'being able to keep a secret a secret'\" いつまでもその秘密を隠しておけること \"The concept 'being able to keep that secret a secret forever\" This concept can be talked about as for instance 'being hard' or 'be- ing impossible', or even'is unnatural', whereas: 秘密を隠しておけるもの \"That which is 'being able to keep a secret a secret'\" or いつまでもその秘密を隠しておけるもの \"That which is 'being able to keep that secret a secret forever\" can only be talked about as existing or not, but that's roughly it. The concept of being able to keep a secret hidden from the rest of the world is something abstract, while the actual act of being able to keep some secret hidden is concrete. For the abstract idea, こ と is used. For the concrete event, も の is used. ばあい 6.2.4 Illustrating a circumstance, case or occasion using",
    "examples": [
      {
        "japanese": "秘密を隠しておけること",
        "english": "\"The concept 'being able to keep a secret a secret'\""
      },
      {
        "japanese": "いつまでもその秘密を隠しておけること",
        "english": "\"The concept 'being able to keep that secret a secret forever\""
      },
      {
        "japanese": "秘密を隠しておけるもの",
        "english": "\"That which is 'being able to keep a secret a secret'\""
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 298,
    "pageEnd": 298,
    "aliases": [
      "Illustrating a circumstance, case or occasion using ばあい (場合)",
      "場合",
      "ケース"
    ]
  },
  {
    "topicId": "language_patterns/indicating_a_moment_of_opportunity_using_しだい_次第",
    "title": "Indicating a moment of opportunity using しだい (次第)",
    "excerpt": "comment is made. 場合 can of course also be used for verb phrases, in which case it follows the 連体形: かね た ばあい ともだち か お金が足りない場合には友達から借ります。 \"'In case (I) don't have enough money, (I)Tl borrow it off (my) friends.\" In this sentence, the clause お金が足り ない, \"[I) do not have enough (sufficient) money', has been turned into a circumstance leading to the comment on it when this should happen. しだい 6.2.5 Indicating a moment of opportunity using 次第 つぎ If we look at the kanji form of this nominaliser we see 次 meaning \"next' だい and 第 meaning \"number\"/\"instance'\". Basically the combination Lい means \"when [some event], [something else]\". For instance: み くだ 見つけ次第、知らせて下さい。 \"Please let (me) know the moment (you) find out' れんようけい This sentence turns the clause 見つけ, the 連用形 for 見つける，\"to discover/find out\", into a moment of opportunity should it occur, where the action to then take is to let someone know of this",
    "examples": [
      {
        "japanese": "かね た ばあい ともだち か"
      },
      {
        "japanese": "お金が足りない場合には友達から借ります。",
        "english": "\"'In case (I) don't have enough money, (I)Tl borrow it off (my) friends.\""
      },
      {
        "japanese": "見つけ次第、知らせて下さい。",
        "english": "\"Please let (me) know the moment (you) find out'"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 299,
    "pageEnd": 299,
    "aliases": [
      "Indicating a moment of opportunity using しだい (次第)",
      "次第",
      "しだい"
    ]
  },
  {
    "topicId": "language_patterns/describing_an_occurrence_using_たび_度",
    "title": "Describing an occurrence using たび (度)",
    "excerpt": "たび 6.2.6 Describing an occurrence using 度 If you want to describe something that occurs or can occur at times, then z び lets you say something general about these occurrences.",
    "examples": [
      {
        "japanese": "ほしぞら み よる おも だ"
      },
      {
        "japanese": "星空を見るたびに、あの夜のことを思い出す。",
        "english": "\"Whenever (I) look up at a starry sky, (I) remember that (special)"
      },
      {
        "japanese": "はじ にほん き じゅうはっさい"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 300,
    "pageEnd": 300,
    "aliases": [
      "Describing an occurrence using たび (度)",
      "たび",
      "度に"
    ]
  },
  {
    "topicId": "language_patterns/incidating_apparent_behaviour_using_まね_真似",
    "title": "Incidating apparent behaviour using まね (真似)",
    "excerpt": "まね 6.2.161 Incidating apparent behaviour using 真似 まね literally means immitation, and it is typically used to indicate appar- ent (and insincere) behaviour.",
    "examples": [
      {
        "japanese": "おとな まね"
      },
      {
        "japanese": "大人の真似はやめるよ。",
        "english": "'Stop acting like an adult."
      },
      {
        "japanese": "かのじよ な"
      }
    ],
    "sourceKind": "direct",
    "confidence": "keyword",
    "sourceId": "maynard_grammar_grammar_reference",
    "pageStart": 307,
    "pageEnd": 307,
    "aliases": [
      "Incidating apparent behaviour using まね (真似)",
      "まね",
      "真似"
    ]
  }
] as const

const MAYNARD_ALIAS_INDEX: Record<string, number[]> = {
  "being:です,だ,ある,いる": [
    0
  ],
  "です": [
    0
  ],
  "だ": [
    0
  ],
  "ある": [
    0
  ],
  "いる": [
    0
  ],
  "がある": [
    0
  ],
  "がいる": [
    0
  ],
  "じゃない": [
    0
  ],
  "じゃありません": [
    0
  ],
  "ではない": [
    0
  ],
  "pronouns:こそあど": [
    1
  ],
  "これ": [
    1
  ],
  "それ": [
    1
  ],
  "あれ": [
    1
  ],
  "どれ": [
    1
  ],
  "ここ": [
    1
  ],
  "そこ": [
    1
  ],
  "あそこ": [
    1
  ],
  "どこ": [
    1
  ],
  "この": [
    1
  ],
  "その": [
    1
  ],
  "あの": [
    1
  ],
  "どの": [
    1
  ],
  "adjectives": [
    2
  ],
  "い-adjective": [
    2
  ],
  "い-adjectives": [
    2
  ],
  "な-adjective": [
    2
  ],
  "な-adjectives": [
    2
  ],
  "形容詞": [
    2
  ],
  "形容動詞": [
    2
  ],
  "basicinflections": [
    3
  ],
  "verb(non-past)": [
    3
  ],
  "dictionaryform": [
    3
  ],
  "う-verb(dictionary)": [
    3
  ],
  "る-verb(dictionary)": [
    3
  ],
  "negative": [
    3
  ],
  "negative-past": [
    3
  ],
  "past": [
    3
  ],
  "ます": [
    3
  ],
  "ません": [
    3
  ],
  "ました": [
    3
  ],
  "ませんでした": [
    3
  ],
  "continuative:てform": [
    4
  ],
  "verbて": [
    4
  ],
  "adjective+て": [
    4
  ],
  "ている": [
    4
  ],
  "てある": [
    4
  ],
  "てしまう": [
    4
  ],
  "てみる": [
    4
  ],
  "てから": [
    4
  ],
  "なくて": [
    4
  ],
  "てよかった": [
    4
  ],
  "ちゃう": [
    4
  ],
  "ていく": [
    4
  ],
  "ていた": [
    4
  ],
  "て初めて": [
    4
  ],
  "requesting:て,てください": [
    5
  ],
  "てください": [
    5,
    5
  ],
  "ください": [
    5
  ],
  "て頂戴": [
    5
  ],
  "お～願う": [
    5
  ],
  "representativelisting:たり": [
    6
  ],
  "たり": [
    6
  ],
  "たり～たり": [
    6
  ],
  "し～し": [
    6
  ],
  "conditional:たら,なら": [
    7
  ],
  "たら": [
    7
  ],
  "なら": [
    7
  ],
  "ならば": [
    7
  ],
  "もし": [
    7
  ],
  "desire": [
    8
  ],
  "たい": [
    8
  ],
  "たがる": [
    8
  ],
  "ほしい": [
    8
  ],
  "欲しい": [
    8
  ],
  "がほしい": [
    8
  ],
  "のがすき": [
    8
  ],
  "好き": [
    8
  ],
  "きらい": [
    8
  ],
  "嫌い": [
    8
  ],
  "pseudo-future:おう/よう": [
    9
  ],
  "ようと思う": [
    9
  ],
  "おうと思う": [
    9
  ],
  "verb[よう]": [
    9
  ],
  "ましょう": [
    9
  ],
  "ませんか": [
    9
  ],
  "hypothetical:えば": [
    10
  ],
  "ば": [
    10
  ],
  "えば": [
    10
  ],
  "なければ": [
    10
  ],
  "ばいい": [
    10
  ],
  "commands": [
    11
  ],
  "命令形": [
    11
  ],
  "な$": [
    11
  ],
  "たまえ": [
    11
  ],
  "なさい": [
    11
  ],
  "ないで": [
    11
  ],
  "そんな": [
    11
  ],
  "こんな": [
    11
  ],
  "あんな": [
    11
  ],
  "どんな": [
    11
  ],
  "passive:れる/られる": [
    12
  ],
  "れる": [
    12
  ],
  "られる": [
    12
  ],
  "passive": [
    12
  ],
  "causative:せる/させる": [
    13
  ],
  "せる": [
    13
  ],
  "させる": [
    13
  ],
  "causative": [
    13
  ],
  "causativepassive:せられる/させられる": [
    14
  ],
  "せられる": [
    14
  ],
  "させられる": [
    14
  ],
  "causative-passive": [
    14
  ],
  "potential": [
    15
  ],
  "ことができる": [
    15
  ],
  "できる": [
    15
  ],
  "得る": [
    15
  ],
  "づらい": [
    15
  ],
  "ぎみ": [
    15
  ],
  "切る": [
    15
  ],
  "抜く": [
    15
  ],
  "聞こえる": [
    15
  ],
  "見える": [
    15
  ],
  "formality:humble/honorificspeechpatterns": [
    16
  ],
  "お～になる": [
    16
  ],
  "いらっしゃる": [
    16
  ],
  "なさる": [
    16
  ],
  "いたす": [
    16
  ],
  "ございます": [
    16
  ],
  "でございます": [
    16
  ],
  "essentialparticles": [
    17
  ],
  "は": [
    17
  ],
  "が": [
    17
  ],
  "も": [
    17
  ],
  "の": [
    17
  ],
  "か": [
    17
  ],
  "を": [
    17
  ],
  "で": [
    17
  ],
  "に": [
    17
  ],
  "へ": [
    17
  ],
  "と": [
    17
  ],
  "や": [
    17
  ],
  "ね": [
    17
  ],
  "よ": [
    17
  ],
  "から": [
    17
  ],
  "まで": [
    17
  ],
  "ごろ": [
    17
  ],
  "emphaticparticles": [
    18
  ],
  "しか": [
    18
  ],
  "ばかり": [
    18
  ],
  "だけ": [
    18
  ],
  "こそ": [
    18
  ],
  "さえ": [
    18
  ],
  "でも": [
    18
  ],
  "くらい": [
    18
  ],
  "ほど": [
    18
  ],
  "など": [
    18,
    49
  ],
  "furtherparticles": [
    19
  ],
  "について": [
    19
  ],
  "として": [
    19
  ],
  "において": [
    19
  ],
  "に関して": [
    19
  ],
  "に対して": [
    19
  ],
  "によって": [
    19
  ],
  "につれて": [
    19
  ],
  "にしたがって": [
    19
  ],
  "にとって": [
    19
  ],
  "に取って": [
    19
  ],
  "から見ると": [
    19
  ],
  "から言うと": [
    19
  ],
  "上": [
    19
  ],
  "以上": [
    19
  ],
  "反面": [
    19
  ],
  "限り": [
    19
  ],
  "向き": [
    19
  ],
  "向け": [
    19
  ],
  "counting": [
    20
  ],
  "number": [
    20
  ],
  "なん+counter": [
    20
  ],
  "一つ": [
    20
  ],
  "二つ": [
    20
  ],
  "いくつ": [
    20
  ],
  "counters": [
    21
  ],
  "counter": [
    21
  ],
  "枚": [
    21
  ],
  "冊": [
    21
  ],
  "本": [
    21
  ],
  "人": [
    21
  ],
  "countingtimerelatedunits": [
    22
  ],
  "時間": [
    22
  ],
  "日": [
    22
  ],
  "週間": [
    22
  ],
  "か月": [
    22
  ],
  "年": [
    22
  ],
  "分": [
    22
  ],
  "comparisons,preferencesandchoice": [
    23
  ],
  "より": [
    23
  ],
  "のほうが": [
    23
  ],
  "どちら": [
    23
  ],
  "どっち": [
    23
  ],
  "あまり": [
    23
  ],
  "binarychoices": [
    24
  ],
  "かどうか": [
    24
  ],
  "comparisonthroughlikeness,andimpressions": [
    25
  ],
  "ように": [
    25
  ],
  "ような": [
    25
  ],
  "みたい": [
    25
  ],
  "らしい": [
    25
  ],
  "そうだ": [
    25
  ],
  "そうです": [
    25
  ],
  "そうに": [
    25
  ],
  "そうな": [
    25
  ],
  "あげく": [
    25
  ],
  "風": [
    25
  ],
  "discussingpossibilities": [
    26
  ],
  "かもしれない": [
    26
  ],
  "でしょう": [
    26
  ],
  "だろう": [
    26
  ],
  "nominalising": [
    27
  ],
  "こと": [
    27
  ],
  "のこと": [
    27
  ],
  "ことがある": [
    27
  ],
  "たことがある": [
    27
  ],
  "backreferralusingの": [
    28
  ],
  "のです": [
    28
  ],
  "んです": [
    28
  ],
  "のだ": [
    28
  ],
  "んだ": [
    28
  ],
  "abstractconceptualisationusingこと(事)": [
    29
  ],
  "ことだ": [
    29
  ],
  "ことなく": [
    29
  ],
  "indicatingaspecifictimeoreventusingとき(時)": [
    30
  ],
  "とき": [
    30
  ],
  "時": [
    30
  ],
  "statinganexpectationusingはず(筈)": [
    31
  ],
  "はず": [
    31
  ],
  "statingasocialexpectationorcustomusingべき": [
    32
  ],
  "べき": [
    32
  ],
  "indicatingamomentintimeusingところ(所)": [
    33
  ],
  "ところ": [
    33
  ],
  "ところで": [
    33
  ],
  "ところが": [
    33
  ],
  "ところに": [
    33
  ],
  "きり": [
    33
  ],
  "statinganintentionusingつ(積)もり": [
    34
  ],
  "つもり": [
    34
  ],
  "statingameaningorsituationalexplanationusingわけ(訳)": [
    35
  ],
  "わけ": [
    35
  ],
  "わけではない": [
    35
  ],
  "describingaway,usingよう(様)": [
    36
  ],
  "ようにする": [
    36
  ],
  "ようがない": [
    36
  ],
  "indicatinganexactmannerusingまま": [
    37
  ],
  "まま": [
    37
  ],
  "statingpurposeusingため(為)": [
    38
  ],
  "ため": [
    38
  ],
  "ために": [
    38
  ],
  "ための": [
    38
  ],
  "talkingabouta'something'usingとい(言)う": [
    39
  ],
  "という": [
    39
  ],
  "って": [
    39
  ],
  "といった": [
    39
  ],
  "とか": [
    39,
    49
  ],
  "いわゆる": [
    39
  ],
  "そういう": [
    39
  ],
  "givingandreceiving": [
    40
  ],
  "てあげる": [
    40
  ],
  "てくれる": [
    40
  ],
  "てもらう": [
    40
  ],
  "あげる": [
    40
  ],
  "くれる": [
    40
  ],
  "もらう": [
    40
  ],
  "indirectspeech": [
    41
  ],
  "と言う": [
    41
  ],
  "と思う": [
    41
  ],
  "と考える": [
    41
  ],
  "とされている": [
    41
  ],
  "と考えられている": [
    41
  ],
  "adverbs": [
    42
  ],
  "いきなり": [
    42
  ],
  "おそらく": [
    42
  ],
  "けっこう": [
    42
  ],
  "せめて": [
    42
  ],
  "ぜんぜん": [
    42
  ],
  "たくさん": [
    42
  ],
  "たちまち": [
    42
  ],
  "つまり": [
    42
  ],
  "どうして": [
    42
  ],
  "どうせ": [
    42
  ],
  "どんどん": [
    42
  ],
  "なお": [
    42
  ],
  "なぜ": [
    42
  ],
  "まず": [
    42
  ],
  "また": [
    42
  ],
  "一応": [
    42
  ],
  "一旦": [
    42
  ],
  "何しろ": [
    42
  ],
  "精々": [
    42
  ],
  "morenegatives": [
    43
  ],
  "ざる": [
    43
  ],
  "ぬ": [
    43
  ],
  "まい": [
    43
  ],
  "verbs": [
    44
  ],
  "他動詞・自動詞": [
    44
  ],
  "自動詞": [
    44
  ],
  "他動詞": [
    44
  ],
  "おわる": [
    44
  ],
  "つづける": [
    44
  ],
  "nouns": [
    45
  ],
  "ら": [
    45
  ],
  "代": [
    45
  ],
  "中": [
    45
  ],
  "気": [
    45
  ],
  "pronouns": [
    46
  ],
  "誰": [
    46
  ],
  "prefixes": [
    47
  ],
  "各": [
    47
  ],
  "真": [
    47
  ],
  "conjunctive": [
    48
  ],
  "つつ": [
    48
  ],
  "っぱなし": [
    48
  ],
  "openchoices": [
    49
  ],
  "か何か": [
    49
  ],
  "なり": [
    49
  ],
  "やら": [
    49
  ],
  "realconceptualisationusingもの(物)": [
    50
  ],
  "もの": [
    50
  ],
  "もん": [
    50
  ],
  "illustratingacircumstance,caseoroccasionusingばあい(場合)": [
    51
  ],
  "場合": [
    51
  ],
  "ケース": [
    51
  ],
  "indicatingamomentofopportunityusingしだい(次第)": [
    52
  ],
  "次第": [
    52
  ],
  "しだい": [
    52
  ],
  "describinganoccurrenceusingたび(度)": [
    53
  ],
  "たび": [
    53
  ],
  "度に": [
    53
  ],
  "incidatingapparentbehaviourusingまね(真似)": [
    54
  ],
  "まね": [
    54
  ],
  "真似": [
    54
  ]
} as const

export function findMaynardDirectRef(pattern: string): MaynardDirectRef | undefined {
  const key = normalizeMaynardAlias(pattern)
  const exact = MAYNARD_ALIAS_INDEX[key]
  if (exact?.length) return MAYNARD_DIRECT_REFS[exact[0]]

  const compactKey = key.replace(/[()\[\]{}+~〜・･]/g, '')
  for (const [alias, indexes] of Object.entries(MAYNARD_ALIAS_INDEX)) {
    if (!alias) continue
    const compactAlias = alias.replace(/[()\[\]{}+~〜・･]/g, '')
    if (compactAlias && (compactKey.includes(compactAlias) || compactAlias.includes(compactKey))) {
      return MAYNARD_DIRECT_REFS[indexes[0]]
    }
  }
  return undefined
}

export function getMaynardDirectRefStats() {
  return { refCount: MAYNARD_DIRECT_REFS.length, aliasCount: Object.keys(MAYNARD_ALIAS_INDEX).length }
}

function normalizeMaynardAlias(value: string): string {
  return value
    .toLowerCase()
    .replace(/[\u3000\s]/g, '')
    .replace(/〜/g, '~')
    .replace(/下さい/g, 'ください')
    .replace(/[“”]/g, '"')
    .replace(/[’]/g, "'")
}
