export const APP_ROUTE_PATHS = [
  '/',
  '/onboarding',
  '/study',
  '/study/review',
  '/study/mistakes',
  '/learn/lessons',
  '/learn/lessons/:cefr/:lessonNumber',
  '/learn/study',
  '/study/jlpt',
  '/practice',
  '/my-content',
  '/settings',
  '/immersion',
  '/learn',
  '/scenarios',
  '/study/grammar',
  '/dev/textbook-qa',
] as const
